---
title: "Operations on flat tables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Operations on flat tables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introduction


```{r}
library(rolap)

file <-
  system.file(
    "extdata",
    "deaths_122_us_cities_1962_2016_mortality_reporting_system.csv",
    package = "rolap"
  )

mrs_ft <-
  read_flat_table_file(name = 'mrs', file)
```


```{r}
usc_ft <-
  flat_table(name = 'us_cities', instances = maps::us.cities) |>
  snake_case() |>
  transform_to_attribute(measures = 'pop',
                         width = 5) |>
  transform_to_attribute(measures = c('lat', 'long'),
                         width = 2,
                         decimal_places = 1) |>
  transform_to_attribute(measures = 'capital')  |>
  lookup_table(pk_attributes = 'name')

```



```{r}
# have to be strings else are considered measures
capital_status <- data.frame(
  code = c('0', '1', '2'),
  status = c('non-capital', 'capital', 'state capital')
)

cs_ft <-
  flat_table(name = 'capital_status', instances = capital_status) |>
  lookup_table(pk_attributes = 'code')
```



```{r}
usc_ft <- usc_ft |>
  join_lookup_table(fk_attributes = 'capital', lookup = cs_ft)
```


```{r}
# function to define a derived column
city_state <- function(table) {
  paste0(table$City, ' ', table$State)
}

mrs_ft <- mrs_ft|>
  add_custom_column(name = 'city_state', definition = city_state)

mrs_ft |>
  check_lookup_table(fk_attributes = 'city_state', lookup = usc_ft)

# 1 Washington DC <- WASHINGTON DC
# 2 Wilimington DE -> Wilmington DE
```


```{r}
usc_ft <- usc_ft |>
  replace_attribute_values(
    attributes = 'name',
    old = c('WASHINGTON DC'),
    new = c('Washington DC')
  )
```


```{r}
mrs_ft <- mrs_ft |>
  replace_attribute_values(
    attributes = c('City', 'city_state'),
    old = c('Wilimington', 'Wilimington DE'),
    new = c('Wilmington', 'Wilmington DE')
  )
```


```{r}
mrs_ft |>
  check_lookup_table(fk_attributes = 'city_state', lookup = usc_ft)
```


```{r}
mrs_ft <- mrs_ft |>
  join_lookup_table(fk_attributes = 'city_state', lookup = usc_ft)
```


```{r}
mrs_ft |>
  get_attribute_names(as_definition = TRUE)
```


```{r}
mrs_ft <- mrs_ft |>
  transform_to_measure(
    attributes = c(
      'Pneumonia and Influenza Deaths',
      'All Deaths',
      '<1 year (all cause deaths)',
      '1-24 years (all cause deaths)',
      '25-44 years',
      '45-64 years (all cause deaths)',
      '65+ years (all cause deaths)'
    )
  ) |>
  select_attributes(
    attributes = c(
      'Year',
      'WEEK',
      'Week Ending Date',
      'REGION',
      'State',
      'City',
      'city_state',
      'status',
      'pop',
      'lat',
      'long'
    )
  )
```


```{r}
l_mrs_ft <- mrs_ft |>
  separate_measures(measures = list(
    c('Pneumonia and Influenza Deaths',
      'All Deaths'),
    c(
      '<1 year (all cause deaths)',
      '1-24 years (all cause deaths)',
      '25-44 years',
      '45-64 years (all cause deaths)',
      '65+ years (all cause deaths)'
    )
  ),
  names = c('mrs_cause', 'mrs_age'))

mrs_cause_ft <- l_mrs_ft[['mrs_cause']]
mrs_age_ft <- l_mrs_ft[['mrs_age']]
```



```{r}
mrs_cause_ft <- mrs_cause_ft |>
  snake_case()
```


```{r}
mrs_age_ft <- mrs_age_ft |>
  transform_to_values(attribute = 'age',
                      measure = 'all_deaths') |>
  snake_case()
```


```{r}
mrs_age_ft <- mrs_age_ft |>
  replace_string(
    attributes = 'age',
    string = ' (all cause deaths)',
    replacement = ''
  )
```


```{r}
sort(unique(mrs_age_ft$table$age))
```

